### ISSUE TITLE
Tag highlighting issue when ternary operators are used

### ISSUE THREAD

**Issue by jacksleight** [robsontenorio/voltage#2]
### Voltage version

1.0.0 beta1

### VSCode version

1.95.3

### Laravel version

11.30.0

### Livewire version

3.5.12

### What happened?

When ternary operators are used either in the PHP class or the template it seems to kick the tag highlighting out:

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    public function test()
    {
        $test = true ? 1 : 0;
    }
}; ?>

<div class="example"></div>
```

Before/After:
![Screenshot 2024-12-02 at 16 21 08](https://github.com/user-attachments/assets/50532c23-48ac-41c7-95db-04b8ccdac68b)
![Screenshot 2024-12-02 at 16 21 00](https://github.com/user-attachments/assets/36ccaffb-47ac-4f49-931d-1f9a885ccc95)

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {}; ?>

<div>
    <div>{{ true ? 1 : 0 }} Tag</div>
</div>
```

![Screenshot 2024-12-02 at 16 24 10](https://github.com/user-attachments/assets/826cd549-01c1-4863-8ab9-a8f6d732cbe2)

**Comment by robsontenorio** [comment]
@jacksleight 

Maybe you have another blades related extensions? Or even something on your settings.json?

Make sure to restart vscode after tweaking. 

For reference, see the extensions I have installed.

![image](https://github.com/user-attachments/assets/2fac7930-bb7a-4870-993b-44525198a695)

**Comment by jacksleight** [comment]
I figured it out, this extension seems to be conflicting with it somehow:

https://marketplace.visualstudio.com/items?itemName=pcbowers.alpine-intellisense

Be amazing if they could work together, but appreciate this might be a bug in that extension not this one.

**Comment by robsontenorio** [comment]
Have added alpine syntax on 1.0.2

**Comment by jacksleight** [comment]
Thanks I'll test it out.

**Comment by jacksleight** [comment]
Works great! I assume this means I don't need the Alpine IntelliSense extension now?

**Comment by robsontenorio** [comment]
Voltage has syntax highlighting covered now 👍
