### ISSUE TITLE
Only Detects Volt Components in the resources/views/livewire directory and not /pages directory

### ISSUE THREAD

**Issue by joshcirre** [robsontenorio/voltage#3]
### Voltage version

1.0.4

### VSCode version

1.94.2

### Laravel version

11

### Livewire version

3.15.7

### What happened?

When trying to use Voltage in Volt components in a Folio application, the extension does not recognize auto-complete of methods or variables unless the Volt component is in the `livewire` directory.

**Comment by robsontenorio** [comment]
@joshcirre  Havent tested on Folio apps. Will give a try soon.

By the way what do you see at output logs? Other features works good?

![image](https://github.com/user-attachments/assets/3bb55899-bd0f-4a01-a746-7bc6a03a1820)

**Comment by joshcirre** [comment]
Sorry for the short issue report. I was putting together a video on the extension and I ran into it not working but I believe it's just the directory settings Since putting the same component in a `livewire` directory fixes everything. 

Here's a Folio component in pages, but then when moving it to the `livewire` directory, everything works as expected. So I believe no features work in the Volt mounted pages directory, but I could be wrong. Hopefully that helps!

https://share.cleanshot.com/1NgLGCB0

**Comment by robsontenorio** [comment]
@joshcirre 

Actually I need to make it smart to look at another folders. Currently it is hardcoded at /views/livewire. That is the issue. Will take a look soon. Thanks for reporting.

**Comment by robsontenorio** [comment]
@joshcirre  Published 1.1.0 that fixes the issue.
